import 'package:hive/hive.dart';

part 'task_model.g.dart'; //MAKE SURE HAS THE SAME NAME AS THIS FILE. this class will be generated by the build runner 

@HiveType(typeId: 10)
class Task extends HiveObject{

  @HiveField(0)
  late String title;

  @HiveField(1)
  late String description;

  @HiveField(2)
  late String category;

  @HiveField(3)
  late bool isCompleted;
  
	//create a switch case function that assigns the category number to the number of points
	//this field can be received by using a function in the views page field to grab the category
  @HiveField(4)
  late DateTime deadline; 

  @HiveField(5)
  late int totalSwords; 

  Task({
    required this.title, 
    required this.description, 
    required this.category, 
    this.isCompleted = false, 
    this.totalSwords = 0,
    required this.deadline}
  );
}
