name: test_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: any

  #GAME ENGINER - Flame
  flame: ^1.17.0

  #LOCAL STORAGE - Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #STATE MANAGEMENT - getX
  get: ^4.6.5
  
  #DESIGN
  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.0.1
  
  #Generate RFC4122 UUIDs
  uuid: ^4.3.3
  
  #ALARM MANAGER
  android_alarm_manager_plus: ^3.0.4

  #Animations exported as JSON
  lottie: ^3.1.0

  #ANIMATION
  animate_do: ^2.0.0

  #Dialogs
  panara_dialogs: ^0.1.4
  flutter_beautiful_popup: ^1.7.0

  #Toast - quick feedback about an operation in a small popup
  ftoast: ^2.0.0

  #Slider drawer
  flutter_slider_drawer: ^2.1.3

  #Date picker
  flutter_datetime_picker: ^1.5.1

  #SVG Pictures
  flutter_svg: ^2.0.10+1

  #Firebse-Firestore
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_auth_mocks: ^0.13.0
  cloud_firestore: ^4.15.8

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_local_notifications: ^16.3.3
  google_fonts: 6.1.0
  mutex: ^3.1.0
  timezone: ^0.9.2
  settings_ui: ^2.0.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.1.11

  flutter_lints: ^3.0.1
  test: ^1.24.9

flutter:
  uses-material-design: true

  #--------------- LOCAL ASSETS ------------------#
  assets:
    - assets/
    - assets/icons/
    - assets/images/avatars/
    - assets/images/backgrounds/
    - assets/images/components/
    - assets/animations/lottie/

  #--------------- LOCAL FONTS ------------------#
  fonts:
    - family: Bebas Neue
      fonts:
        - asset: assets/fonts/BebasNeue-Bold.otf
        - asset: assets/fonts/BebasNeue-Book.otf
        - asset: assets/fonts/BebasNeue-Light.otf
        - asset: assets/fonts/BebasNeue-Regular.otf