name: test_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.0.1
  uuid: ^4.3.2
  android_alarm_manager_plus: ^3.0.4

  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_local_notifications: ^16.3.3
  google_fonts: ^6.1.0
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.1.11

  flutter_lints: ^3.0.1
  test: ^1.24.9

flutter:
  uses-material-design: true