name: test_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: ^3.1.1

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_slidable: ^3.0.1

  english_words: ^4.0.0
  provider: ^6.0.0
  google_fonts: ^6.1.0
  firebase_auth: ^4.17.4
  firebase_core: ^2.25.4
  firebase_auth_mocks: ^0.13.0
  cloud_firestore: ^4.15.8
  color_blindness: ^0.1.2
  theme_provider: ^0.6.0
  settings_ui: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4
  hive_generator: ^2.0.1
  build_runner: ^2.1.11

  flutter_lints: ^3.0.1
  rxdart: ^0.27.7

flutter:
  uses-material-design: true